# Generated by Django 3.1.5 on 2021-01-31 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "title",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("is_archived", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("B", "In Backlog"),
                            ("T", "To Do Now"),
                            ("I", "In Progress"),
                            ("W", "Waiting For Review"),
                            ("R", "Resolved"),
                            ("C", "Closed"),
                        ],
                        default="B",
                        max_length=1,
                    ),
                ),
                ("estimated_time", models.DurationField(blank=True, null=True)),
                ("spent_time", models.DurationField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_active": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        limit_choices_to={"is_archived": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="issues.category",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="reported_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
