name: Code Quality
on: [push, pull_request]
jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Black
        uses: lgeiger/black-action@master
        with:
          args: ". --check"
      - name: PyLint
        uses: cclauss/GitHub-Action-for-pylint@master
  django-test:
    name: Django Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Setup environment and Run Tests
        run: |
          python3 -m pip install --upgrade pip
          pip3 install poetry
          poetry install --no-root
          source `poetry env info --path`/bin/activate
          python3 manage.py test
        env:
          DJANGO_SETTINGS_MODULE: trkr.settings.production
          DJANGO_SECRET_KEY: ABCDEFGIJK0123456789ABCDEFGIJK0123456789ABCDEFGIJK
